### ISSUE TITLE
TimeLine: JS Error

### ISSUE THREAD

**Issue by melloware** [primefaces/showcase-facelift#94]
https://www.primefaces.org/showcase/ui/data/timeline/allEvents.xhtml

On the All Events Error if you go to the Showcase its getting a JS Error in the console. @jasonex7 @christophs78 Can you investigate please?

**Comment by christophs78** [comment]
https://www.primefaces.org/showcase/ui/data/timeline/dragdrop.xhtml has this issue too. Seems like something regarding to Drag´n´Drop is broken.

**Comment by christophs78** [comment]
Maybe a bug in vis-timeline 6.2.0. The JS error is raised by the vis-timeline-JS, we renamed to timeline.js.

**Comment by christophs78** [comment]
@jasonex7 : No, it´s our own (=PrimeFaces) bug. 1-timeline.js, line 364
There we do `$(el).droppable(droppableOpts);` 
And el was not defined before.

@melloware: Think we should transfer this bug to PrimeFaces.

**Comment by melloware** [comment]
Yes let’s open in on the main PF issues

**Comment by christophs78** [comment]
This bug was introduced with https://github.com/primefaces/primefaces/commit/7be389313032a191dd25796b986c4282e162fe2c#diff-28cd7b7805f212735ee6518b1cc7cf93

The old bindEvents had a el-parameter, the new _bindItemsEvent misses this parameter:
![grafik](https://user-images.githubusercontent.com/10461942/69847362-2aff3d00-1277-11ea-9933-3ec1b0bc22b1.png)

**Comment by melloware** [comment]
I opened https://github.com/primefaces/primefaces/issues/5388 and I will fix it.

**Comment by jasonex7** [comment]
> @jasonex7 : No, it´s our own (=PrimeFaces) bug. 1-timeline.js, line 364
> There we do $(el).droppable(droppableOpts);
> And el was not defined before.

Yeah, it was a mistake.
